# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('typeID', models.CharField(max_length=64)),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('sumPrice', models.FloatField()),
                ('discount', models.FloatField()),
                ('position', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('describe', models.TextField()),
            ],
        ),
    ]
