# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
