# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easet', '0002_auto_20170908_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True),
        ),
    ]
